docs: update pre-bundling guide
vitejs/docs-ja pull request #319
Opened 2022-02-25 12:35 UTC by jay-es

resolve #317

vitejs/vite@33f9671 の取り込みと翻訳です。

2022-02-25 12:36 UTC, jay-es commented on guide/dep-pre-bundling.md
> +(this will be run only when your dependencies or config have changed)
表示されるメッセージなので英語に戻しました

2022-03-05 01:28 UTC, naokie commented on guide/dep-pre-bundling.md
> +(this will be run only when your dependencies or config have changed)
あ、そうですね。
ここではツールが出力するメッセージをそのままがよいです 👍🏼

2022-03-05 01:42 UTC, naokie requested changes
1つ日本語としての不自然さから提案してみます。

2022-03-05 01:42 UTC, naokie commented on guide/dep-pre-bundling.md
> +モノレポの設定では、依存関係は同じリポジトリからのリンクされたパッケージの可能性があります。Vite は `node_modules` から解決されない依存関係を自動的に検出し、リンクされた依存関係をソースコードとして扱います。リンクされた依存関係をバンドルしようとはせず、代わりにリンクされた依存関係の依存関係リストを分析します。
```suggestion
モノレポの設定では、依存関係は同じリポジトリからのリンクされたパッケージの可能性があります。Vite は `node_modules` から解決されない依存関係を自動的に検出し、リンクされた依存関係をソースコードとして扱います。リンクされた依存関係をバンドルしようとはせず、代わりにリンクされた依存関係のリストを分析します。
```

日本語として不自然な部分があるので一部省略したいです。
「依存関係」が連続して出てくるので読み安さ優先で。
例えば、「日本の日本地図」「家系の家系図」のように省略できるのではと。

2022-03-11 11:24 UTC, jay-es commented
@naokie ありがとうございます。suggestion を適用しました:pray:

2022-05-13 13:05 UTC, merged