docs: vite only replace __dirname, __filename, import.meta.url in cjs
vitejs/docs-ja pull request #361
Opened 2022-03-25 01:06 UTC by hiro-lapis

resolve #359 

https://github.com/vitejs/vite/commit/f44859379277b7a3e99529be275022733dc69ef1 の反映です

2022-03-25 12:35 UTC, jay-es requested changes
```
::: tip NOTE
```

2022-03-25 12:35 UTC, jay-es commented on config/index.md
> +Vite は **CommonJS** と**TypeScript** の設定ファイルの `__filename`, `__dirname`, `import.meta.url` を置換することに注意してください。これらを変数名として使用すると、エラーになります:
`::: tip NOTE` 部分も反映お願いします:pray:
（https://github.com/vitejs/vite/commit/f44859379277b7a3e99529be275022733dc69ef1 の 39-40 行目も同様）

```suggestion
::: tip 注意
Vite は **CommonJS** と**TypeScript** の設定ファイルの `__filename`, `__dirname`, `import.meta.url` を置換することに注意してください。これらを変数名として使用すると、エラーになります:
```

2022-03-25 14:19 UTC, hiro-lapis commented
@jay-es 
失礼しました。
手数ですが、指摘もらった箇所を修正したので再度チェックしていただけますか🙇‍♂️

2022-03-26 13:30 UTC, jay-es approved these changes
修正ありがとうございます！:pray:

2022-03-26 13:31 UTC, merged