docs: classic worker
vitejs/docs-ja pull request #362
Opened 2022-03-25 16:19 UTC by hiro-lapis

resolve #360 

https://github.com/vitejs/vite/commit/4e0b61593a0eba97a901f996619c5e1aae4a7b68 の反映です

2022-03-26 13:34 UTC, jay-es requested changes
翻訳は問題なさそうですが、389-390 も反映お願いします:bow:

2022-03-27 03:19 UTC, hiro-lapis commented
@jay-es
たびたび失礼しました。
指摘いただいた389-390も翻訳修正させていただいたので、チェックしていただけますか🙇‍♂️

2022-03-28 11:52 UTC, jay-es requested changes

2022-03-28 11:52 UTC, jay-es commented on guide/features.md
> +より詳細なワーカのバンドル設定については [Worker Options](/config/#worker-options) を見てください。
若干ニュアンスが変わってしまっているので修正お願いします:pray:
```suggestion
すべてのワーカをバンドルする設定についての詳細は [Worker Options](/config/#worker-options) を見てください。
```

2022-03-28 15:02 UTC, hiro-lapis commented
@jay-es 
指摘の通り意味合いが変わってましたね。。。
提案もらった表現に修正しました🙇‍♂️

2022-03-29 11:11 UTC, jay-es approved these changes
LGTM!

2022-03-29 11:11 UTC, merged