feat(dev): expose APIs for client-server communication
vitejs/docs-ja pull request #373
Opened 2022-03-31 14:57 UTC by hiro-lapis

resolve #363

2022-04-01 13:19 UTC, jay-es requested changes
何点か修正お願いします:pray:
翻訳が完了したら、機械翻訳などを使って原文と意味が合っているか確認していただけると助かります:bow:

2022-04-01 13:19 UTC, jay-es commented on guide/api-hmr.md
> +カスタムイベントを背後にある Vite の開発サーバーへ送信します。
```suggestion
カスタムイベントを Vite の開発サーバへ送り返します。
```

2022-04-01 13:19 UTC, jay-es commented on guide/api-hmr.md
> +詳細は [クライアントサーバーとのコミュニケーション](/guide/api-plugin.html#client-server-communication) を参照してください。
communication はこの場合「通信」とするのがよさそうです
```suggestion
詳細は [クライアントサーバーとの通信](/guide/api-plugin.html#client-server-communication) を参照してください。
```

2022-04-01 13:19 UTC, jay-es commented on guide/api-plugin.md
> +Vite の 2.9 から、プラグインによりクライアントとのコミュニケーションに役立つ機能をいくつか提供しています。
「通信」に変更
```suggestion
## クライアントサーバーとの通信

Vite の 2.9 から、プラグインによりクライアントとの通信に役立つ機能をいくつか提供しています。
```

2022-04-01 13:19 UTC, jay-es commented on guide/api-plugin.md
> +プラグイン側からは `server.ws.send` を使うことで全クライアントへイベントをブロードキャストすることができます:
カタカナだと分かりにくいため「配信」などに変更するとよさそうです
```suggestion
プラグイン側からは `server.ws.send` を使うことで全クライアントへイベントを配信することができます:
```

2022-04-01 13:19 UTC, jay-es commented on guide/api-plugin.md
> +クライアントからサーバーへイベントをブロードキャストする時は [`hot.send`](/guide/api-hmr.html#hot-send-event-payload) を使うことができます:
send → 送信
```suggestion
クライアントからサーバーへイベント送信する時は [`hot.send`](/guide/api-hmr.html#hot-send-event-payload) を使うことができます:
```

2022-04-01 13:19 UTC, jay-es commented on guide/api-plugin.md
> +この時、サーバー側では `server.ws.on` を使ってイベントをリッスンします。
```suggestion
この時、サーバー側では `server.ws.on` を使ってイベントをリッスンします:
```

2022-04-01 15:05 UTC, hiro-lapis commented on guide/api-hmr.md
> +カスタムイベントを背後にある Vite の開発サーバーへ送信します。
コメントいただいた箇所を修正しました。

不適切な訳があり度々手数かけてすみません。
アドバイスいただいた通り、以降は機械翻訳で確認を徹底します🙇‍♂️

2022-04-02 05:29 UTC, hiro-lapis commented
@jay-es
アドバイスいただいた通り、以降は機械翻訳で確認するようにします🙇‍♂️
修正させてもらったので、都合がよろしい時に再レビューいただいてもいいでしょうか。

2022-04-02 14:29 UTC, jay-es requested changes
522, 544行目の文末をコロンに変更お願いします:pray:

2022-04-02 14:29 UTC, jay-es commented on guide/api-plugin.md
> +クライアント側では、[`hot.on`](/guide/api-hmr.html#hot-on-event-cb) を使用してイベントをリッスンします。
```suggestion
クライアント側では、[`hot.on`](/guide/api-hmr.html#hot-on-event-cb) を使用してイベントをリッスンします:
```

2022-04-03 03:43 UTC, hiro-lapis commented
@jay-es 
ケアレスミスすみません🙇‍♂️
修正しました。

2022-04-04 10:55 UTC, merged