feat: new hook configurePreviewServer
vitejs/docs-ja pull request #442
Opened 2022-05-20 04:16 UTC by hiro-lapis

resolve #421 
https://github.com/vitejs/vite/commit/20ea9999765ea372c20acc39e05cd81b98c9f6fe の反映です

2022-05-20 12:28 UTC, jay-es requested changes
レビューしました。
お手すきで修正お願いします:pray:

2022-05-20 12:28 UTC, jay-es commented on guide/api-plugin.md
> +- **Kind:** `async`, `sequential`
他に合わせて修正お願いします:pray:
```suggestion
- **型:** `(server: { middlewares: Connect.Server, httpServer: http.Server }) => (() => void) | void | Promise<(() => void) | void>`
- **種類:** `async`, `sequential`
```

2022-05-20 12:28 UTC, jay-es commented on guide/api-plugin.md
> +      // 他のミドルウェアがインストールされた後に
called の訳を追加
```suggestion
      // 他のミドルウェアがインストールされた後に呼び出される
```

2022-05-20 12:28 UTC, jay-es commented on guide/api-plugin.md
> +  プレビューサーバを除いて [`configureServer`](/guide/api-plugin.html#configureserver) と同じです。[connect](https://github.com/senchalabs/connect) サーバとその配下にある [http server](https://nodejs.org/api/http.html) を提供します。`c
```suggestion
  [`configureServer`](/guide/api-plugin.html#configureserver) と同じですがプレビューサーバ用です。[connect](https://github.com/senchalabs/connect) サーバとその配下にある [http server](https://nodejs.org/api/http.html) を提供します。`configureServer` と同様に、`configurePreviewServer` フックは他のミドルウェアがインストールされる前に呼び出されます。他のミドルウェアをインストールした**後に**ミドルウェアをインジェクトしたい場合は、`configurePreviewServer` から関数を返すことで、内部のミドルウェアがインストールされた後に呼び出されるようにすることができます:
```

2022-05-21 11:38 UTC, hiro-lapis commented on guide/api-plugin.md
> +  プレビューサーバを除いて [`configureServer`](/guide/api-plugin.html#configureserver) と同じです。[connect](https://github.com/senchalabs/connect) サーバとその配下にある [http server](https://nodejs.org/api/http.html) を提供します。`c
but for の訳が間違ってましたね😅
指摘ありがとうございます、修正します！

2022-05-21 11:39 UTC, hiro-lapis commented on guide/api-plugin.md
> +- **Kind:** `async`, `sequential`
失礼しました。修正します！

2022-05-21 11:39 UTC, hiro-lapis commented on guide/api-plugin.md
> +      // 他のミドルウェアがインストールされた後に
修正します！

2022-05-21 11:40 UTC, hiro-lapis commented
@jay-es 
修正しました。
手隙の際に再レビューいただけますか🙇‍♂️

2022-05-23 11:37 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-05-23 11:38 UTC, merged