feat!: rework import.meta.glob
vitejs/docs-ja pull request #446
Opened 2022-05-21 11:31 UTC by hiro-lapis

resolve #423 
https://github.com/vitejs/vite/commit/330e0a90988509454e31067984bf0cdbe2465325 の反映です

2022-05-23 11:36 UTC, jay-es requested changes
レビューしました。
3箇所修正お願いします:pray:

2022-05-23 11:36 UTC, jay-es commented on guide/features.md
> +### Glob インポートの注意事項
空行追加お願いします
```suggestion
### Glob インポートの注意事項

```

2022-05-23 11:36 UTC, jay-es commented on guide/features.md
>  - Glob パターンは外側の引用符と同じ引用符の文字列（つまり `'`, `"`, `` ` ``）を含むことはできません。例えば `'/Tom\'s files/**'` は、代わりに `"/Tom's files/**"` を使用してください。
この行は削除お願いします
```suggestion
```

2022-05-23 11:36 UTC, jay-es commented on guide/features.md
> +- Glob のマッチングは [`fast-glob`](https://github.com/mrmlnc/fast-glob) を介して行われます。サポートされている Glob パターンについては、その[ドキュメント](https://github.com/mrmlnc/fast-glob#pattern-syntax)を確認してください。
以前の翻訳部分ですが、リンクの箇所を原文に合わせました
```suggestion
- Glob のマッチングは [`fast-glob`](https://github.com/mrmlnc/fast-glob) を介して行われます。[サポートされている Glob パターン](https://github.com/mrmlnc/fast-glob#pattern-syntax)については、ドキュメントを確認してください。
```

2022-05-27 04:34 UTC, hiro-lapis commented on guide/features.md
> +### Glob インポートの注意事項
失礼しました。
修正します！

2022-05-27 04:36 UTC, hiro-lapis commented on guide/features.md
> +- Glob のマッチングは [`fast-glob`](https://github.com/mrmlnc/fast-glob) を介して行われます。サポートされている Glob パターンについては、その[ドキュメント](https://github.com/mrmlnc/fast-glob#pattern-syntax)を確認してください。
こちらの方が適切ですね、修正します！

2022-05-27 04:40 UTC, hiro-lapis commented
@jay-es 
レビューありがとうございます。
指摘いただいた箇所の修正をpushさせていただいたので、再レビューお願いします🙇‍♂️

2022-05-27 11:12 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-05-27 11:12 UTC, merged