docs: note for inconsistency between dev and build
vitejs/docs-ja pull request #454
Opened 2022-05-28 06:53 UTC by hiro-lapis

resolve #426 
https://github.com/vitejs/vite/commit/095543fcc5fd978e8b56fd68a7bc1785db339ee7 の反映です。

2022-05-28 12:03 UTC, jay-es requested changes

2022-05-28 12:03 UTC, jay-es commented on config/index.md
> +  開発環境とビルド環境で `define` の実装が異なるので、矛盾を回避すために、いくつかの使い方を避ける必要があります。
タイポ修正お願いします:pray:
```suggestion
  開発環境とビルド環境で `define` の実装が異なるので、矛盾を回避するために、いくつかの使い方を避ける必要があります。
```

2022-05-29 02:25 UTC, hiro-lapis commented on config/index.md
> +  開発環境とビルド環境で `define` の実装が異なるので、矛盾を回避すために、いくつかの使い方を避ける必要があります。
ケアレス失礼しました🙇‍♂️
修正したので確認してもらえますか。

2022-05-30 11:43 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-05-30 11:43 UTC, merged