docs: explain dynamic import
vitejs/docs-ja pull request #457
Opened 2022-05-28 07:50 UTC by hiro-lapis

resolve #429 
https://github.com/vitejs/vite/commit/774bd286c6666878003ac34f7e256c539a84f9bd の反映です。

2022-05-28 12:10 UTC, jay-es requested changes
1点修正お願いします:pray:

2022-05-28 12:10 UTC, jay-es commented on guide/features.md
> +[glob import](#glob-import) と同様に、 Vite は変数付きの動的インポートをサポートしています。
ここの with は「手段」として訳すのがよさそうです
```suggestion
[glob import](#glob-import) と同様に、 Vite は変数を使った動的インポートをサポートしています。
```

2022-05-29 02:29 UTC, hiro-lapis commented on guide/features.md
> +[glob import](#glob-import) と同様に、 Vite は変数付きの動的インポートをサポートしています。
提案いただいた通りですね！
修正します！

2022-05-30 11:44 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-05-30 11:44 UTC, merged