docs: use vitepress next
vitejs/docs-ja pull request #462
Opened 2022-05-29 03:24 UTC by hiro-lapis

resolve #441
https://github.com/vitejs/vite/commit/52539011bc6350e376ed15eca4c408579deb363d の反映です。

2022-05-29 03:25 UTC, hiro-lapis commented on index.md
> +> TODO: Home Page feature is not ready in VitePress Next just yet! So this page looks broken for now.
そもそも翻訳にはTODOを載せる必要はないのかな、、、とは思ったものの反映しました。
また、TODOコメントなので原文をそのまま反映しました。

2022-05-30 11:54 UTC, jay-es requested changes
`.vitepress` ディレクトリの修正や、vitepress バージョンの変更もお願いします:bow:
（pnpm-lock.yaml ではなく yarn.lock の差分ができる）

2022-05-31 13:11 UTC, jay-es commented
@hiro-lapis ビルドエラー解消のためにパッケージアップデートしました。
package.json や yarn.lock がコンフリクトしないよう、最新の origin/main を取り込んでから続きの作業をお願いします:pray:

2022-05-31 13:11 UTC, jay-es commented
@hiro-lapis ビルドエラー解消のためにパッケージアップデートしました。
package.json や yarn.lock がコンフリクトしないよう、最新の origin/main を取り込んでから続きの作業をお願いします:pray:

2022-06-03 11:59 UTC, jay-es approved these changes
ありがとうございます！
#477 の修正が完了したらマージします
（PR の差分が分かりやすいように2つのコミットに分ける）

2022-06-04 11:46 UTC, merged

2022-06-04 11:50 UTC, jay-es commented
コンフリクトしてしまい、解消していただくのも悪いので #477 だけマージします:bow: