docs: vitepress next updates
vitejs/docs-ja pull request #477
Opened 2022-06-02 15:01 UTC by hiro-lapis

resolve #447 

https://github.com/vitejs/vite/commit/a4cc80b67a855628185f2dd8073c24614d5bb5f5 の反映です。

2022-06-02 15:04 UTC, hiro-lapis commented on index.md
> +layout: home
かっこいいですね！
![スクリーンショット 2022-06-02 23 12 15](https://user-images.githubusercontent.com/53115998/171660118-b9506d33-df6c-4bab-9a6f-9a7a5a87c3f0.png)

日本語では下記のようになります。
![image](https://user-images.githubusercontent.com/53115998/171660269-74d94cfe-66b0-465a-8686-2a6c6e8cab47.png)

2022-06-02 15:06 UTC, hiro-lapis commented on index.md
> +  tagline: 最先端をいく開発環境を構築しましょう
`Get ready for a development environment that can finally catch up with you.`
の役に悩みました。
`catch up with you.`を`最先端をいく`に意訳しましたが、よりいい訳があれば提案おねがいします🙇‍♂️

2022-06-02 15:09 UTC, hiro-lapis commented on .vitepress/config.ts
> +      text: '日本語',
翻訳サイトなので`text`を日本語にしました。

2022-06-03 11:56 UTC, jay-es requested changes
2点修正お願いします:pray:

2022-06-04 01:41 UTC, hiro-lapis commented
@jay-es 
失礼しました。
こちら修正したので確認いただけますか🙇‍♂️

2022-06-04 11:44 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-06-04 11:50 UTC, merged