docs: update for default target change
vitejs/docs-ja pull request #478
Opened 2022-06-04 02:12 UTC by hiro-lapis

resolve #439 
https://github.com/vitejs/vite/commit/e68c25cf464428fb42e622fd3749f0daf1b943ab の反映です

2022-06-04 02:14 UTC, hiro-lapis commented on guide/build.md
> +本番バンドルではモダンな JavaScript のサポートを前提としています。Vite はデフォルトでは [ネイティブ ES モジュール](https://caniuse.com/es6-module) と [ネイティブ ESM の動的インポート](https://caniuse.com/es6-module-dynamic-import) および [`import.meta`](https:/
以前の訳してくれた方はリンクテキストを訳さずにおいたようですが、
他箇所との統一感を考えて、今回は訳しています。

2022-06-04 11:56 UTC, jay-es requested changes
1点だけ修正お願いします:pray:

2022-06-04 11:56 UTC, jay-es commented on guide/assets.md
>  ::: warning esbuild ターゲット設定が必要
こちらの行も変更お願いします:pray:
```suggestion
::: warning `target` は `es2020` 以降が必要
```

2022-06-04 12:41 UTC, hiro-lapis commented
@jay-es 
失礼しました。
修正1箇所だけだったので、suggestを受け入れる形で修正させてもらいました!

2022-06-06 12:29 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-06-06 12:29 UTC, merged