docs: split config pages and more
vitejs/docs-ja pull request #492
Opened 2022-06-12 05:22 UTC by hiro-lapis

resolve #451 
https://github.com/vitejs/vite/commit/5791f5ddec8b279d3e915eed8d329c5c4b49708f の反映です。

2022-06-12 05:29 UTC, hiro-lapis commented on package.json
> +    "vitepress": "1.0.0-draft.4",
本家の対応する順序は`"vitepress": "1.0.0-draft.3",`=> `"vitepress": "1.0.0-draft.4",`だったのですが、
こちらでは6からデグレする形になってしまいました。

対応順序を間違ってしまいすみません🙇‍♂️

#465 でもバージョンを更新しているので、
このPRをmainマージ後に、追って#465 をマージすれば解消できるかと思うのですが、どうしましょうか？

2022-06-12 05:29 UTC, hiro-lapis commented on config/index.md
>  ```
index.mdの各種項目を、本家に倣い、以下の対応しつつページ分割しました。
・訳はそのまま移す
・移行前の文章(コードスニペット含む)は半角2つのスペースがあったが、移行にあたってスペースを削除
・移行後の#は一つ減らし、見出しを1ランク上にする
・本家の分割後の各種ページと、日本語ドキュメントの各種ページの行数が一致していることを確認

2022-06-12 05:30 UTC, hiro-lapis commented on config/build-options.md
> +  チャンクサイズ警告の制限値（kb 単位）。
本家でもここは半角スペース2つ残ってたため、同じように対応しました。

2022-06-12 05:31 UTC, hiro-lapis commented on config/server-options.md
> +  - `lerna.json`
本家でもここは半角スペース2つ残ってたため、同じように対応しました。

2022-06-12 05:32 UTC, hiro-lapis commented on config/shared-options.md
> +  ](https://webpack.js.org/configuration/resolve/#resolvesymlinks)
本家でもこのsymlinksの箇所は半角スペースが残ってたため、同じように対応しました。

2022-06-14 12:43 UTC, jay-es requested changes
いつもありがとうございます。
何点か修正お願いします:pray:

2022-06-14 12:43 UTC, jay-es commented on config/preview-option.md
> +- **デフォルト:** [`server.proxy`](#server_proxy)
```suggestion
- **デフォルト:** [`server.proxy`](./server-options#server_proxy)
```

2022-06-14 12:43 UTC, jay-es commented on config/ssr-options.md
> +- **関連:** [外部 SSR](/guide/ssr#外部-ssr)
本家は順番が変わっていました
```suggestion
# SSR オプション

- **関連:** [外部 SSR](/guide/ssr#外部-ssr)

:::warning 実験的な機能
SSR オプションは、マイナリリースで調整される可能性があります。
:::
```

2022-06-14 12:43 UTC, jay-es commented on .vitepress/config.ts
> +              text: '共有オプション',
各ページのタイトルに合わせてください:pray:
```suggestion
              text: '共通オプション',
```

2022-06-14 12:43 UTC, jay-es commented on .vitepress/config.ts
> +              text: 'サーバーオプション',
```suggestion
              text: 'サーバオプション',
```

2022-06-14 12:43 UTC, jay-es commented on .vitepress/config.ts
> +              text: 'プレビューオプション',
（これはページのタイトルを変えてもいいかも知れない）
```suggestion
              text: 'プレビューのオプション',
```

2022-06-17 03:59 UTC, hiro-lapis commented on package.json
> +    "vitepress": "1.0.0-draft.4",
戻しました。`yarn docs`でページが表示されることも確認できました。

2022-06-17 04:02 UTC, hiro-lapis commented on .vitepress/config.ts
> +              text: 'サーバーオプション',
修正しました。

2022-06-17 04:03 UTC, hiro-lapis commented on .vitepress/config.ts
> +              text: 'プレビューオプション',
修正しました。

2022-06-17 04:23 UTC, hiro-lapis commented on config/ssr-options.md
> +- **関連:** [外部 SSR](/guide/ssr#外部-ssr)
失礼しました。修正しました！

2022-06-17 04:26 UTC, hiro-lapis commented
@jay-es 
お待たせしてすみません🙇‍♂️
一通りサイト内リンクの動作確認し、修正しました。

再度確認おねがいします。

2022-06-17 13:06 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-06-17 13:06 UTC, merged