feat: better config __dirname support
vitejs/docs-ja pull request #519
Opened 2022-06-22 03:51 UTC by hiro-lapis

resolve #489 
https://github.com/vitejs/vite/commit/51e9195fe94657e7ab14a22a0e7de338ad0724fd の反映です。

2022-06-22 12:02 UTC, jay-es requested changes

2022-06-22 12:02 UTC, jay-es commented on config/index.md
> +Vite は設定ファイルとその依存関係内に `__filename`, `__dirname` を注入することに注意してください。これら変数をトップレベルで宣言するとエラーになります:
前回のレビュー漏れですが、原文に「注意してください」のニュアンスはないので修正お願いします:pray:
```suggestion
Vite は設定ファイルとその依存関係内に `__filename`, `__dirname` を注入します。これらの変数をトップレベルで宣言するとエラーになります:
```

2022-06-22 23:25 UTC, hiro-lapis commented
@jay-es 
suggest受け入れて修正させてもらいました。
確認いただけますか🙇‍♂️

2022-06-23 12:18 UTC, jay-es approved these changes
ありがとうございました:bow:

2022-06-23 12:18 UTC, merged