feat: legacy options to revert to v2 strategies
vitejs/docs-ja pull request #544
Opened 2022-06-30 23:16 UTC by hiro-lapis

resolve #500 
https://github.com/vitejs/vite/commit/993b842cff9f743cb969e749e7052a2cbb665919 の反映です。

2022-07-01 10:16 UTC, jay-es requested changes
2箇所修正お願いします！:pray:

2022-07-01 10:16 UTC, jay-es commented on guide/migration.md
> +これらのオプションは実験中かつ非推奨としてマークされています。将来の v3 マイナーで semver を尊重することなく削除される可能性があります。使用する場合は、Vite のバージョンを固定するようにしてください。
```suggestion
これらのオプションは実験的機能かつ非推奨としてマークされています。将来の v3 マイナーで semver を尊重することなく削除される可能性があります。使用する場合は、Vite のバージョンを固定するようにしてください。
```

2022-07-01 10:16 UTC, jay-es commented on guide/migration.md
>  ## ビルドでの変更
```suggestion
### ビルドでの変更
```

2022-07-02 23:23 UTC, hiro-lapis commented on guide/migration.md
> +これらのオプションは実験中かつ非推奨としてマークされています。将来の v3 マイナーで semver を尊重することなく削除される可能性があります。使用する場合は、Vite のバージョンを固定するようにしてください。
失礼しました、修正します🙇‍♂️

2022-07-02 23:23 UTC, hiro-lapis commented on guide/migration.md
>  ## ビルドでの変更
失礼しました、修正します🙇‍♂️

2022-07-02 23:23 UTC, hiro-lapis commented on guide/migration.md
> +これらのオプションは実験中かつ非推奨としてマークされています。将来の v3 マイナーで semver を尊重することなく削除される可能性があります。使用する場合は、Vite のバージョンを固定するようにしてください。
失礼しました、修正します🙇‍♂️

2022-07-02 23:23 UTC, hiro-lapis commented on guide/migration.md
> +これらのオプションは実験中かつ非推奨としてマークされています。将来の v3 マイナーで semver を尊重することなく削除される可能性があります。使用する場合は、Vite のバージョンを固定するようにしてください。
失礼しました、修正します🙇‍♂️

2022-07-02 23:23 UTC, hiro-lapis commented on guide/migration.md
>  ## ビルドでの変更
失礼しました、修正します🙇‍♂️

2022-07-04 09:47 UTC, jay-es requested changes
すみません、1点見落としていました:bow:
59行目にも `#` を追加お願いします:pray:

2022-07-06 05:45 UTC, hiro-lapis commented
遅れてすみません、
59行目の修正も終わったので確認いただけますか🙇‍♂️

2022-07-06 10:27 UTC, jay-es requested changes
たびたびすみません:bow:
もう1箇所修正をお願いします:bow:

2022-07-10 12:42 UTC, hiro-lapis commented
度々遅れてすみません、修正させてもらいました！

2022-07-11 11:48 UTC, jay-es approved these changes
いえいえ、いつもありがとうございます:bow:

2022-07-11 11:48 UTC, merged