docs: cleanup changes
vitejs/docs-ja pull request #646
Opened 2022-08-01 16:50 UTC by sapphi-red

resolve #561
https://github.com/vitejs/vite/commit/07aef1b4c02a64732b31b00591d2d9d9c8025aab の反映です

一か所行数の修正をしています

2022-08-01 16:51 UTC, sapphi-red commented on guide/static-deploy.md
> +
ここの空行が抜けていて行数がずれていたので修正しました 👍

2022-08-02 11:17 UTC, jay-es requested changes
guide/build.md の L56 を `export default` に修正お願いします:pray:
https://github.com/vitejs/vite/commit/07aef1b4c02a64732b31b00591d2d9d9c8025aab#diff-4a49b457ff0fce41061261711fc1d5e95385af670880cebae5fca2d4807103f0R56

2022-08-02 12:28 UTC, sapphi-red commented
修正しました :pray:

2022-08-03 11:20 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-08-03 11:24 UTC, merged