docs: `resolve.alias` for SSR externalized deps
vitejs/docs-ja pull request #671
Opened 2022-08-06 08:26 UTC by sapphi-red

resolve #611
https://github.com/vitejs/vite/commit/b2a493131873422f96089601669ab104d68e80a7  の反映です

2022-08-07 13:09 UTC, jay-es requested changes

2022-08-07 13:09 UTC, jay-es commented on config/shared-options.md
> +SSR の外部化された依存関係のエイリアスを設定した場合は、実際の `node_modules` パッケージのエイリアスを設定することをお勧めします。[Yarn](https://classic.yarnpkg.com/en/docs/cli/add/#toc-yarn-add-alias) と [pnpm](https://pnpm.js.org/en/aliases) の両方で `npm:`
リンク追加お願いします:pray:
```suggestion
[SSR の外部化された依存関係](/guide/ssr#外部-ssr)のエイリアスを設定した場合は、実際の `node_modules` パッケージのエイリアスを設定することをお勧めします。[Yarn](https://classic.yarnpkg.com/en/docs/cli/add/#toc-yarn-add-alias) と [pnpm](https://pnpm.js.org/en/aliases) の両方で `npm:` のエイリアスをサポートします。
```

2022-08-08 05:13 UTC, sapphi-red commented on config/shared-options.md
> +SSR の外部化された依存関係のエイリアスを設定した場合は、実際の `node_modules` パッケージのエイリアスを設定することをお勧めします。[Yarn](https://classic.yarnpkg.com/en/docs/cli/add/#toc-yarn-add-alias) と [pnpm](https://pnpm.js.org/en/aliases) の両方で `npm:`
ありがとうございます :pray:

2022-08-08 09:35 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-08-08 09:35 UTC, merged