Config ページ Build Options 後半の翻訳
vitejs/docs-ja pull request #74
Opened 2021-08-04 13:20 UTC by jay-es

2021-08-05 12:49 UTC, jay-es commented on config/index.md
> +- **関連:** [外部 SSR](/guide/ssr#ssr-externals)
以前の翻訳もれ

2021-08-07 04:29 UTC, naokie requested changes

2021-08-07 04:29 UTC, naokie commented on config/index.md
> +- **関連:** [ライブラリモード](/guide/build#library-mode)
```suggestion
- **関連:** [ライブラリモード](/guide/build#ライブラリモード)
```

アンカーリンクが翻訳したものに変わるため、修正する必要ありますね。

2021-08-07 04:29 UTC, naokie commented on config/index.md
> +  ライブラリとしてビルドします。ライブラリではエントリとして HTML を使用できないため、`entry` が必要です。`name` は公開されているグローバル変数で、`formats` に `'umd'` や `'iife'` が含まれている場合に必要です。デフォルトの `formats` は `['es', 'umd']` です。デフォルトの `fileName` は package.js
> `fileName` is the name of the package file output,

これに対応する訳が抜け落ちてしまってるようです。

2021-08-07 12:37 UTC, jay-es commented on config/index.md
> +  ライブラリとしてビルドします。ライブラリではエントリとして HTML を使用できないため、`entry` が必要です。`name` は公開されているグローバル変数で、`formats` に `'umd'` や `'iife'` が含まれている場合に必要です。デフォルトの `formats` は `['es', 'umd']` です。デフォルトの `fileName` は package.js
本当ですね、気づいてませんでした。。。ありがとうございます:pray:

2021-08-10 12:33 UTC, naokie approved these changes
LGTM です！

2021-08-10 12:33 UTC, merged