Config ページ Server Options 後半の翻訳
vitejs/docs-ja pull request #76
Opened 2021-08-05 13:30 UTC by jay-es

2021-08-07 04:41 UTC, naokie requested changes
いつもありがとうございます。
1つだけミスあったので、お願いします！

2021-08-07 04:41 UTC, naokie commented on config/index.md
> +  - `'html'` は Vite 自体の HTML 配信ロジックを有効にします。
ここで行が1つずれてしまったので、 L:465 の空行は削除お願いします 🙇🏼

2021-08-07 12:37 UTC, jay-es commented on config/index.md
> +  - `'html'` は Vite 自体の HTML 配信ロジックを有効にします。
確認漏れてました。ありがとうございます:pray:

2021-08-10 12:32 UTC, naokie approved these changes
LGTM です！

2021-08-10 12:33 UTC, merged