docs: update versionLinks, outlineTitle and docFooter
vitejs/docs-ja pull request #915
Opened 2023-03-08 11:57 UTC by Naoto-Ida

こんにちは。本レポに貢献しようと思い[貢献方法](https://github.com/vitejs/docs-ja/blob/main/CONTRIBUTING.md#%E8%B2%A2%E7%8C%AE%E6%96%B9%E6%B3%95)を見てIssueを探していたんですが、初っ端から大きな変更を加えることに少し不安を感じるので小さめのPRを送らせてもらいます。

今後アサインされていないIssueを通して貢献していければなと思っています。

2023-03-08 13:36 UTC, jay-es requested changes
プルリクエストありがとうございます！
何点か修正お願いします:pray:

2023-03-08 13:36 UTC, jay-es commented on .vitepress/config.ts
> +      next: '次へ',
こちら Vue.js の日本語ドキュメントと同じ文言に変更お願いします:pray:
```suggestion
      prev: '前のページ',
      next: '次のページ',
```

2023-03-08 13:36 UTC, jay-es commented on .vitepress/config.ts
> +          text: 'Vite 4 ドキュメンテーション (リリース)',
サイト内を確認したところ、「ドキュメンテーション」という表現は使われていなかったので、「ドキュメント」に変更お願いします:pray:
（ついでにカッコを全角に）
```suggestion
          text: 'Vite 4 ドキュメント（リリース）',
```

2023-03-08 18:23 UTC, Naoto-Ida commented on .vitepress/config.ts
> +      next: '次へ',
サジェスチョンありがとうございます！
確かにVue.jsの日本語ドキュメントだとそう書いてますね。
次回からそっちも確認してからプルリク送ります👍

2023-03-09 10:23 UTC, jay-es reviewed
修正ありがとうございます！
一箇所なおっていなかったので対応お願いします:pray:

2023-03-09 10:23 UTC, jay-es commented on .vitepress/config.ts
> +          text: 'Vite 4 ドキュメント (リリース）',
```suggestion
          text: 'Vite 4 ドキュメント（リリース）',
```

2023-03-09 21:11 UTC, Naoto-Ida commented
修正箇所の指摘ありがとうございます🙏
これで大丈夫だと良いです！

2023-03-10 12:04 UTC, jay-es approved these changes
ご対応ありがとうございます:pray:

2023-03-10 12:04 UTC, merged